language: c

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_COVERAGE=On

script:
  - make # && make test
  - ctest --verbose
  - make gcov

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov -t "1b2f01c2-c875-4c07-8a73-9aff59b3d292"